---
- hosts: localhost
  connection: local
  user: ehrenschwan
  become: true

  gather_facts: false

  tasks:
    - name: make sure the pacman cache is up to date
      pacman:
        update_cache: yes

    - name: install the base packages needed
      pacman:
        name:
          - vim
          - tmux
          - firefox
          - qtile
          - alacritty
          - stow
        state: present

    - name: clone dotfiles
      git:
        repo: git@github.com:LucaSchwan/dotfiles.git
        dest: /home/ehrenschwan/dotfiles
        key_file: /home/ehrenschwan/.ssh/id_ed25519
      become_user: ehrenschwan

    - name: making config script executable
      file:
        dest: /home/ehrenschwan/dotfiles/enable.sh
        mode: a+x

    - name: execute config script
      shell:
        cmd: ./home/ehrenschwan/dotfiles/enable.sh
        args:
          chdir: /home/ehrenschwan/dotfiles
      register: command_output

    - debug:
      var: command_output.stdout_lines
